# Generated by Django 4.0.4 on 2022-05-17 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('some_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player_choice',
            old_name='player_x',
            new_name='player',
        ),
        migrations.RemoveField(
            model_name='player_choice',
            name='player_y',
        ),
    ]
