# Generated by Django 4.0.4 on 2022-05-28 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('some_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='done_or_not',
            field=models.ForeignKey(default='False', on_delete=django.db.models.deletion.RESTRICT, to='some_app.doneornot'),
        ),
    ]
