# Generated by Django 4.0.4 on 2022-05-29 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('some_app', '0002_alter_todolist_done_or_not'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='done_or_not',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, to='some_app.doneornot'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='to_do_message',
            field=models.CharField(max_length=120),
        ),
    ]
