# Generated by Django 4.0.4 on 2022-05-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('some_app', '0002_rename_player_x_player_choice_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_choice',
            name='player',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
