# Generated by Django 4.0.4 on 2022-05-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('some_app', '0003_alter_todolist_done_or_not_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='to_do_message',
            field=models.CharField(max_length=100),
        ),
    ]
