# Generated by Django 4.0.4 on 2022-05-20 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('some_app', '0003_alter_player_choice_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='password',
            field=models.CharField(default='Asd123', max_length=50, validators=[django.core.validators.MinLengthValidator(6)]),
            preserve_default=False,
        ),
    ]
