# Generated by Django 4.0.4 on 2022-06-01 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('some_app', '0005_alter_todolist_to_do_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='done_or_not',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='some_app.doneornot'),
        ),
    ]
