# Generated by Django 4.0.4 on 2022-05-20 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('some_app', '0005_choice_alter_grid_choice_grid_choice1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice1',
            new_name='choice',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice2',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice3',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice4',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice5',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice6',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice7',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice8',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice9',
        ),
    ]
