# Generated by Django 4.0.4 on 2022-05-20 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('some_app', '0006_rename_choice1_choice_choice_remove_choice_choice2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice_two',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_two', models.CharField(max_length=5)),
            ],
        ),
        migrations.RenameModel(
            old_name='Choice',
            new_name='Choice_one',
        ),
        migrations.RenameField(
            model_name='choice_one',
            old_name='choice',
            new_name='choice_one',
        ),
        migrations.AlterField(
            model_name='grid_choice',
            name='grid_choice2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='some_app.choice_two'),
        ),
    ]
