# Generated by Django 4.0.4 on 2022-05-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('some_app', '0007_choice_two_rename_choice_choice_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid_choice',
            name='grid_choice1',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='grid_choice',
            name='grid_choice2',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='grid_choice',
            unique_together={('grid_choice1', 'grid_choice2')},
        ),
        migrations.DeleteModel(
            name='Choice_one',
        ),
        migrations.DeleteModel(
            name='Choice_two',
        ),
    ]
