# Generated by Django 4.0.4 on 2022-06-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('some_app', '0011_alter_todolist_to_do_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='to_do_message',
            field=models.CharField(error_messages={'max_length': 'Please enter 5 letters per To-Do, Danke you.'}, max_length=5),
        ),
    ]
