# Generated by Django 4.0.4 on 2022-06-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('some_app', '0012_alter_todolist_to_do_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='to_do_message',
            field=models.CharField(max_length=5),
        ),
    ]
